name: FacialXAI
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - numpy==2.2.0
    - matplotlib==3.9.3
    - pandas==2.2.3
    - seaborn==0.13.2
    - scipy==1.14.1
    - jupyterlab==4.3.3
    - wordcloud==1.9.4